### ISSUE TITLE
Downsample vertices when creating vtks

### ISSUE THREAD

**Issue by bcipolli** [binarybottle/roygbiv#6]
Currently, performance isn't great:
- When viewing a single hemisphere with the `destrieux` parcellation causes my rather new macbook pro to load the CPU--enough where the machine gets very hot and runs the fan.
- With megabytes of vtk data to download, load time is non-trivial (1-5 seconds or longer).
- When embedding these figures in other pages, performance can tank (I tried this with `impress.js` last night, for example.

It would be great to have simple downsampling of vertices when creating VTKs for visualizations, and to manually test which downsamplings would still look good in the demo.

@binarybottle any suggestions on downsampling schemes? Perhaps sequential elimination: every `N` vertices, eliminate the last `M` of them (50% would be N=2, M=1).

**Comment by bcipolli** [comment]
Eliminating some % of faces was a bad idea lol:  
![image](https://cloud.githubusercontent.com/assets/4072455/10288862/493e103e-6b50-11e5-9d84-a33fd472abe8.png)

**Comment by binarybottle** [comment]
Please try mindboggle.guts.mesh.py's decimate() or decimate_file().

**Comment by bcipolli** [comment]
Fixed in https://github.com/binarybottle/roygbiv/commit/49157b300cfcaf209b639d063706ab419f940baa
